import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    apiSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'REST API',
            link: {
                type: 'generated-index',
                title: 'REST API',
                description: 'Explore the Saiki REST API endpoints for programmatic interaction.',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rest',
                },
            ],
        },
        'websocket',
        {
            type: 'category',
            label: 'Node.js SDK',
            link: {
                type: 'generated-index',
                title: 'Node.js SDK API Reference',
                description: 'Complete technical API reference for the Saiki Node.js SDK.',
            },
            items: ['nodejs-sdk', 'saiki-agent', 'utilities', 'events', 'types'],
        },
    ],
};

export default sidebars;
