import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    apiSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'REST API',
            link: {
                type: 'generated-index',
                title: 'REST API',
                description: 'Explore the Saiki REST API endpoints for programmatic interaction.',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rest',
                },
            ],
        },
        'websocket',
        {
            type: 'category',
            label: 'TypeScript SDK',
            link: {
                type: 'generated-index',
                title: 'TypeScript SDK API Reference',
                description:
                    'Complete technical API reference for the Saiki TypeScript/JavaScript SDK.',
            },
            items: ['saiki-agent', 'mcp-manager', 'events', 'types'],
        },
    ],
};

export default sidebars;
