import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    apiSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'REST API',
            link: {
                type: 'generated-index',
                title: 'REST API',
                description: 'Explore the Saiki REST API endpoints for programmatic interaction.',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rest',
                },
            ],
        },
        'websocket',
    ],
};

export default sidebars;
