import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manual sidebar configuration for better organization and aesthetics
    tutorialSidebar: [
        // Entry Point
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
                title: 'Getting Started',
                description: 'Quickly set up Saiki and start automating with natural language.',
            },
            items: [{ type: 'autogenerated', dirName: 'getting-started' }],
        },

        // Understanding Saiki
        {
            type: 'category',
            label: 'Learn & Concepts',
            items: [
                'learn/what-is-an-ai-agent',
                'learn/how-do-ai-agents-work',
                'learn/agents-vs-workflows',
                'learn/mcp',
                'learn/tools',
            ],
        },

        // Setup & Configuration
        {
            type: 'category',
            label: 'Configuring Saiki',
            items: [
                'configuring-saiki/overview',
                {
                    type: 'category',
                    label: 'LLM Configuration',
                    items: [
                        'configuring-saiki/llm/index',
                        'configuring-saiki/llm/configuration',
                        'configuring-saiki/llm/providers',
                    ],
                },
                'configuring-saiki/mcpServers',
                'configuring-saiki/storage',
            ],
        },

        // Basic Usage
        {
            type: 'category',
            label: 'User Guide',
            items: ['user-guide/cli', 'user-guide/web-playground', 'user-guide/deployment'],
        },

        // Development - Building Applications (now top-level)
        {
            type: 'category',
            label: 'Building with Saiki',
            items: [{ type: 'autogenerated', dirName: 'building-with-saiki' }],
        },

        // Development - API Documentation (now top-level)
        {
            type: 'category',
            label: 'API Reference',
            items: [{ type: 'autogenerated', dirName: 'api' }, 'mcp-manager'],
        },

        // Architecture - New Position: Second from last
        {
            type: 'category',
            label: 'Architecture',
            link: {
                type: 'generated-index',
                title: 'Saiki Architecture',
                description: 'Explore the high-level and technical architecture of Saiki.',
            },
            items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },

        // Contributing
        {
            type: 'category',
            label: 'Contributing',
            items: [{ type: 'autogenerated', dirName: 'contribution-guide' }],
        },
    ],
};

export default sidebars;
