import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manual sidebar configuration for better organization
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            items: ['getting-started/intro', 'getting-started/examples-demos'],
        },
        {
            type: 'category',
            label: 'Learn',
            items: [
                'learn/what-is-an-ai-agent',
                'learn/how-do-ai-agents-work',
                'learn/agents-vs-workflows',
                'learn/mcp',
                'learn/tools',
            ],
        },
        {
            type: 'category',
            label: 'Configuring Saiki',
            items: [
                'configuring-saiki/configuration',
                'configuring-saiki/llm',
                'configuring-saiki/llm-providers',
                'configuring-saiki/mcpServers',
            ],
        },
        {
            type: 'category',
            label: 'User Guide',
            items: [
                'user-guide/cli',
                'user-guide/web-playground',
                'user-guide/development',
                'user-guide/api',
                'user-guide/deployment',
            ],
        },
        {
            type: 'category',
            label: 'Architecture',
            items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },
        {
            type: 'category',
            label: 'Contribution Guide',
            items: [{ type: 'autogenerated', dirName: 'contribution-guide' }],
        },
    ],
};

export default sidebars;
