import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manual sidebar configuration for better organization and aesthetics
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
                title: 'Getting Started',
                description: 'Quickly set up Saiki and start automating with natural language.',
            },
            items: [{ type: 'autogenerated', dirName: 'getting-started' }],
        },
        {
            type: 'category',
            label: 'Guides',
            link: {
                type: 'generated-index',
                title: 'Guides',
                description: 'Practical guides for using and building with Saiki.',
            },
            items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
        {
            type: 'category',
            label: 'Tutorials',
            link: {
                type: 'generated-index',
                title: 'Tutorials',
                description: 'Tutorials for using Saiki',
            },
            items: [{ type: 'autogenerated', dirName: 'tutorials' }],
        },
        {
            type: 'category',
            label: 'Examples & Demos',
            link: {
                type: 'generated-index',
                title: 'Examples & Demos',
                description: 'Examples and demos of Saiki in action',
            },
            items: [{ type: 'autogenerated', dirName: 'examples-demos' }],
        },
        {
            type: 'category',
            label: 'Concepts',
            link: {
                type: 'generated-index',
                title: 'Concepts',
                description: 'Core concepts for understanding Saiki.',
            },
            items: [{ type: 'autogenerated', dirName: 'concepts' }],
        },
        {
            type: 'category',
            label: 'Architecture',
            link: {
                type: 'generated-index',
                title: 'Architecture',
                description: 'Technical and conceptual information about Saiki.',
            },
            items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },
        {
            type: 'category',
            label: 'Community',
            link: {
                type: 'generated-index',
                title: 'Community',
                description: 'Get involved in the Saiki community.',
            },
            items: [{ type: 'autogenerated', dirName: 'community' }],
        },
    ],
};

export default sidebars;
